# install: conda env create -f ba_env.yaml
# update: conda env update -f ba_env.yaml --prune

name: ba_core_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - setuptools
  - pip
  - ipykernel
  - nb_conda
  - pydantic
  - ffmpeg
  - numpy
  - pandas
  - scipy
  - pyarrow
  - opencv
  - matplotlib
  - natsort
  - tqdm
  # dev packages
  - black
  - pytest
  - mkdocs-material
  - mkdocstrings-python
  - pip:
      - -e "."
